### ISSUE TITLE
"autoplantcrops" adjustable plant delay

### ISSUE THREAD

**Issue by Satramohh** [Tr4nter/auto-plant-crop#11]
Hi, i have a question, is it possible to add a little delay or adjustable delay for "autoplantcrops" via command?
I have a problem when i collect all crops it repleaces it without any problem but... On my server they get warning about my CPS becouse of it and it is a problem for me :P

**Comment by Tr4nter** [comment]
Thanks for your suggestion, I will be adding it soon, i will give further notices on this issue once im done

**Comment by Tr4nter** [comment]
it is done, https://modrinth.com/mod/auto-plant-crops/version/1.1.5
