### ISSUE TITLE
[suggestion] add better settings 

### ISSUE THREAD

**Issue by katipatataki** [Tr4nter/auto-plant-crop#12]
The current way of choosing which setting do you want to have enable is too confusing. So PLS add a better settings GUI like other mods. It will help a lot and even more if you add more settings in the future.

**Comment by Tr4nter** [comment]
Making a settings screen is way too voodoo for the mod's mission statements but despite so I still tried, after a whole day of trying to make an option screen and make it compatible with ModMenu, the way of creating UI elements and buttons between 1.19 and 1.20.2 are way too far apart to be able to make a one file mod that could support multiple versions, and that would make it harder to add new options, that is, having to update and make each file for each different versions.

If you're editing the settings manually by navigating to your .minecraft server, then I recommend changing the mod's settings through custom made commands provided by the mod, if It's still too confusing for you, I recommend reading the mod's description on Modrinth without skipping a word or personally contact me on discord: Tr4nt

Thanks for your suggestion.
