### ISSUE TITLE
legit mode for delay "autoplantcrops"

### ISSUE THREAD

**Issue by Satramohh** [Tr4nter/auto-plant-crop#13]
Hi, last time i've asked about a delay for "autoplantcrops", and you did it fast which i'm really thankful for that.

What you did was when you destroy a crop it will auto plant new one after "x"ms, it does it after every destroyed crop without a queue. What i had i mind was that it will do a queue for the next new crop like, 1st crop will be auto planted after "50"ms, when 1st crop is done it will wait another "50"ms after that it will plants a 2nd one, wait "50"ms then 3rd one etc... It will look more natural and not like a minigun seed planter lik it is now :P

If you didn't understand what i wrote, ask me and i try to explain it better, i've tried my best to explain it.
Maybe you can add it as new option for enable or disable that will override main delay setting.

**Comment by Tr4nter** [comment]
https://modrinth.com/mod/auto-plant-crops/version/fstKFg2E

Thanks for your suggestion, I fixed it, please test it out and see whether if It's working for you. this issue will stay open,

**Comment by Satramohh** [comment]
Yes, this is what i was thinking about :). Thank you for your fast respond and fix <3
