### ISSUE TITLE
Crash on 1.19.4 when mining the stem of a pumpkin

### ISSUE THREAD

**Issue by paintingofblue** [Tr4nter/auto-plant-crop#5]
I'm able to reproduce this consistently and it seems to happen exclusively when mining the stem of a pumpkin. I've attached two crash logs, and a video demonstrating this bug

https://github.com/Tr4nter/auto-plant-crop/assets/90877067/fcf9f9df-798a-4235-b584-e8b68f990bdd
[crash-2023-06-16_16.16.41-client.txt](https://github.com/Tr4nter/auto-plant-crop/files/11765933/crash-2023-06-16_16.16.41-client.txt)
[crash-2023-06-16_16.18.03-client.txt](https://github.com/Tr4nter/auto-plant-crop/files/11765934/crash-2023-06-16_16.18.03-client.txt)

**Comment by Tr4nter** [comment]
Thanks for the bug report, im working on it

**Comment by Tr4nter** [comment]
Hello, bug has been fixed.! [new version](https://github.com/Tr4nter/auto-plant-crop/releases)
